export * from './Separator'
export * from './BasicModal';
export * from './Confirm';
export * from './Label';
export * from  './BarTruts';
export * from  './GridGames';
export * from './BannerAdd';
export * from './NoResult';
export * from './Pagination';