export const ENV={
    SERVER_HOST:"http://localhost:1337",
    API_URL:"http://localhost:1337/api",
    ENDPOINS:{
        AUTH:{
            REGISTER:"auth/local/register",
            LOGIN:"auth/local"
        },
        USERS_ME:"users/me",
        USERS:"users",
        PLATFORM:"plataforms",
        ADDRESS:"addresses",
        GAME:"games",
        WISHLIST:"wishlists",
        PAYMENT_ORDER:"payment-order",
        ORDERS:"orders"
    },
    TOKEN:"token",
    CART:"cart",
    STRIPE_TOKEN:"pk_test_51NYsbqEU1itYkmMAia4GfAJextBmeEL6ZaIj0pFCh9KbGyKarx9ZZN5MdsyHlPucTFMLmRRBqbjzeSmkpKUnuvTT00SIqcUTHb"
}